### PR TITLE
Add foreman setup files

### PR DESCRIPTION
**Pull request by otsubo**

### CODE REVIEW

**Comment by otsubo** [comment]
*How to export foreman to upstart*

```bash
sudo foreman export upstart /etc/init --app dakoku --user leus --env .env
```

*start upstart*

```bash
# sudo initctl reload-configuration
# sudo initctl list | grep dakoku
sudo initctl start dakoku
```

*stop upstart*
```bash
sudo initctl stop dakoku
```

**Comment by furushchev** [comment]
We can use pm2 instead.
foreman does not handle with memory leak problem of nodejs.

**Comment by wkentaro** [comment]
He have error on his environment when running `pm2 pm2.json` but `bash launch.sh` does work. That's why he need to use foreman instead of pm2.

> foreman does not handle with memory leak problem of nodejs.

Also, using foreman, we does not depends on nodejs programs.

**Comment by furushchev** [comment]
ok so please
- remove pm2 related staff.
- add https://github.com/furushchev/dakoku/pull/1#issuecomment-160567935

**Pull request merged**
